### ISSUE TITLE
Buchungen mit "Google Duo" und "Telefon" scheinen nicht zu gehen

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#165]
Wenn ich mit der Kontaktmöglichkeit "Google Duo" oder "Telefon" buchen möchte bekomme ich einen Fehler, mit den gleichen angegebenen Daten aber anderen Kontaktmöglichkeiten geht`s:
![image](https://user-images.githubusercontent.com/11029373/77854897-46f6f900-71ed-11ea-9ce5-ca424d7ce4c3.png)

**Comment by zalintyre** [comment]
```
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: de.qaware.mercury.business.shop.InvalidContactTypeException: Invalid contact type 'TELEFON'
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at de.qaware.mercury.business.shop.ContactType.parse(ContactType.java:32) ~[classes!/:na]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at de.qaware.mercury.rest.reservation.ReservationController.createReservation(ReservationController.java:48) ~[classes!/:na]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at de.qaware.mercury.rest.reservation.ReservationController$$FastClassBySpringCGLIB$$cdb7053b.invoke(<generated>) ~[classes!/:na]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:120) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at de.qaware.mercury.rest.reservation.ReservationController$$EnhancerBySpringCGLIB$$2e35cd4d.createReservation(<generated>) ~[classes!/:na]
Mar 29 18:45:10 lokaler-kaufen-vm java[21010]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
...
```

**Comment by phxql** [comment]
vmtl Frontend-Bug

**Comment by dashuber** [comment]
jap, ist gefixt
