### ISSUE TITLE
javax.mail.SendFailedException: Invalid Addresses;

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#74]
```
[Request processing failed; nested exception is org.springframework.mail.MailSendException: Failed messages: javax.mail.SendFailedException: Invalid Addresses;
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: nested exception is:
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: com.sun.mail.smtp.SMTPAddressFailedException: 504 5.5.2 <JKLJLKJ@KJHJ>: Recipient address rejected: need fully-qualified address
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: ; message exceptions (1) are:
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: Failed message 1: javax.mail.SendFailedException: Invalid Addresses;
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: nested exception is:
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: com.sun.mail.smtp.SMTPAddressFailedException: 504 5.5.2 <JKLJLKJ@KJHJ>: Recipient address rejected: need fully-qualified address
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: ] with root cause
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: org.springframework.mail.MailSendException: Failed messages: javax.mail.SendFailedException: Invalid Addresses;
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: nested exception is:
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: com.sun.mail.smtp.SMTPAddressFailedException: 504 5.5.2 <JKLJLKJ@KJHJ>: Recipient address rejected: need fully-qualified address
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:491) ~[spring-context-support-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:323) ~[spring-context-support-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:312) ~[spring-context-support-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at de.qaware.mercury.mercury.business.email.impl.EmailSenderImpl.sendEmail(EmailSenderImpl.java:35) ~[classes!/:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at de.qaware.mercury.mercury.business.email.impl.EmailServiceImpl.sendCustomerReservationConfirmation(EmailServiceImpl.java:60) ~[classes!/:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at de.qaware.mercury.mercury.business.reservation.impl.ReservationServiceImpl.createReservation(ReservationServiceImpl.java:59) ~[classes!/:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at de.qaware.mercury.mercury.business.reservation.impl.ReservationServiceImpl$$FastClassBySpringCGLIB$$12ef0831.invoke(<generated>) ~[classes!/:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at de.qaware.mercury.mercury.business.reservation.impl.ReservationServiceImpl$$EnhancerBySpringCGLIB$$6cbc3ba3.createReservation(<generated>) ~[classes!/:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at de.qaware.mercury.mercury.rest.reservation.ReservationController.createReservation(ReservationController.java:40) ~[classes!/:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:772) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:120) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at de.qaware.mercury.mercury.rest.reservation.ReservationController$$EnhancerBySpringCGLIB$$12756b55.createReservation(<generated>) ~[classes!/:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
Mär 23 18:03:33 lokaler-kaufen-vm java[31768]: at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by phxql** [comment]
Eventuell einfach ignorieren. Email-Adresse validieren ist nicht so einfach.

**Comment by phxql** [comment]
Hab nen regex dazugebaut, der besser validiert (zumindest dass die domain noch eine top level domain hat). Sollte damit erstmal passen.
