### ISSUE TITLE
Shop anlegen mit existierender Email-Adresse liefert 500

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#89]
```
är 24 11:40:04 lokaler-kaufen-vm java[5082]: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "shop_login_email_key"
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: Detail: Key (email)=(foo@lokaler.kaufen) already exists.
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510) ~[postgresql-42.2.10.jar!/:42.2.10]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245) ~[postgresql-42.2.10.jar!/:42.2.10]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311) ~[postgresql-42.2.10.jar!/:42.2.10]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447) ~[postgresql-42.2.10.jar!/:42.2.10]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368) ~[postgresql-42.2.10.jar!/:42.2.10]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159) ~[postgresql-42.2.10.jar!/:42.2.10]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125) ~[postgresql-42.2.10.jar!/:42.2.10]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.4.2.jar!/:na]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar!/:na]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3235) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3760) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:na]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1352) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:443) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3202) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2370) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183) ~[hiberna
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40) ~[hibernate-core-5.4.12.
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534) ~[spring-orm-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743) ~[spring-tx-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711) ~[spring-tx-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:631) ~[spring-tx-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385) ~[spring-tx-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at de.qaware.mercury.mercury.business.shop.impl.ShopServiceImpl$$EnhancerBySpringCGLIB$$8cd18066.create(<generated>) ~[classes!/:na]
Mär 24 11:40:04 lokaler-kaufen-vm java[5082]: at de.qaware.mercury.mercury.rest.shop.ShopController.createShop(ShopController.java:79) ~[classes!/:na]
```

**Comment by phxql** [comment]
-> Vor dem Shop anlegen prüfen, ob Mail schon existiert. Falls ja, Fehler an Frontend melden. Frontend muss dann Fehler anzeigen.

**Comment by phxql** [comment]
Gefixt im Backend. API gibt nun `HTTP 409` mit so einem Body:

```
{
  "id": "e23c9456-cee0-40d4-b018-5180368f78fd",
  "code": "SHOP_ALREADY_EXISTS",
  "message": "A shop with the email address 'foo@bar.org' already exists"
}
```

**Comment by dashuber** [comment]
Im frontend kommt jetzt auch der entsprechende Hinweis, wenn das backend einen 409er liefert
